import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Provider } from 'jotai';

const open_sans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DwellDone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body className={`${open_sans.className} bg-floral-white`}>
          <Header/>
          {children}
          <Footer/>
        </body>
      </Provider>
    </html>
  );
}
